name: GH actions demo
on:
  push:
    branches:
    - main
    paths-ignore:
    - .github
  pull_request:
    branches:
    - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by ${{github.event_name}}"
          echo "Current branch is ${{github.ref}}"
      - uses: actions/checkout@v4
      - name: List repo files
        run: |
          tree
